package com.timothychia.faces;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.text.method.ScrollingMovementMethod;
import android.util.Log;
import android.widget.TextView;

import com.android.volley.AuthFailureError;
import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.JsonObjectRequest;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.HashMap;
import java.util.Map;

public class DatabaseManagementActivity extends AppCompatActivity {

    private static final String LOG_TAG =  MainActivity.class.getSimpleName();

    private RequestQueue mRequestQueue;
    private TextView mTextView;


    private String app_id = "a1731ed8";
    private String app_key = "d3a579a339de2805b54e53dcd72ee40c";
    final String gallery_name = "People";


    final String  url_gallery_list = "https://api.kairos.com/gallery/list_all";
    final String  url_gallery_view = "https://api.kairos.com/gallery/view";
    final String  url_view_subject = "https://api.kairos.com/gallery/view_subject";
    final String  url_gallery_remove = "https://api.kairos.com/gallery/remove";
    final String  url_gallery_remove_subject = "https://api.kairos.com/gallery/remove_subject";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_database_management);

        mTextView = (TextView) findViewById(R.id.textView2);
        mTextView.setMovementMethod(new ScrollingMovementMethod());

        mRequestQueue =  RequestQueueSingleton.getInstance(this.getApplicationContext()).getRequestQueue();

        gallery_list();
    }


    private void gallery_list(){
        // build json parameters
        JSONObject param = new JSONObject();
        try {
            param.put("gallery_name",gallery_name);
        } catch (JSONException e) {
            e.printStackTrace();
        }

        // build the POST request to enroll
        JsonObjectRequest jReq = new JsonObjectRequest(Request.Method.POST, url_gallery_view,param,
                new Response.Listener() {
                    // online tutorial doesn't use "Object response", but android studio won't recognize it as an override otherwise
                    public void onResponse(Object response) {
                        // Display the first 500 characters of the response string.
//                        mTextView.setText(mCurrentPhotoPath +"Enrolled with Response: "+ response.toString());
                        JSONObject response_json = (JSONObject) response;
                        try {
                            JSONArray subject_ids_json = response_json.getJSONArray("subject_ids");
                            String subject_ids_string =  subject_ids_json.join("\n");
                            mTextView.setText(subject_ids_string);
//                            Log.d(LOG_TAG, subject_ids_string);
                       } catch (JSONException e) {
                            mTextView.setText("An error occurred.");
                            Log.d(LOG_TAG, "Error in gallery_list().");
                            Log.d(LOG_TAG, "Response received to Recognize request:" + response.toString());
                            e.printStackTrace();
                        }
                    }
                }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
//                mTextView.setText(mCurrentPhotoPath +"That didn't work!");
            }
        }){
            @Override
            // online tutorial uses some strange syntax in the angular brackets. Changed it to this instead.
            public Map<String, String> getHeaders() throws AuthFailureError {
                HashMap<String, String> headers = new HashMap<String, String>();
                headers.put("Content-Type", "application/json");
                headers.put("app_id",app_id);
                headers.put("app_key", app_key);
                return headers;
            }
        };

        // Add the request to the RequestQueue.
        mRequestQueue.add(jReq);
    }

    // remove the subject in the gallery with a subject_id generated by...um...
    private void remove_subject(){
        // build json parameters
        JSONObject param = new JSONObject();
        try {
            param.put("gallery_name",gallery_name);
            param.put("subject_id","tempname");
        } catch (JSONException e) {
            e.printStackTrace();
        }

        // build the POST request to enroll
        JsonObjectRequest jReq = new JsonObjectRequest(Request.Method.POST, url_gallery_remove_subject,param,
                new Response.Listener() {
                    // online tutorial doesn't use "Object response", but android studio won't recognize it as an override otherwise
                    public void onResponse(Object response) {
                        // Display the first 500 characters of the response string.
//                        mTextView.setText(mCurrentPhotoPath +"Enrolled with Response: "+ response.toString());
                        JSONObject response_json = (JSONObject) response;
//                        try {
//                            JSONArray subject_ids_json = response_json.getJSONArray("subject_ids");
//                            String subject_ids_string =  subject_ids_json.join("\n");
//                            mTextView.setText(subject_ids_string);
//                            Log.d(LOG_TAG, subject_ids_string);
//                        } catch (JSONException e) {
//                            mTextView.setText("An error occurred.");
//                            Log.d(LOG_TAG, "Error in gallery_list().");
//                            Log.d(LOG_TAG, "Response received to Recognize request:" + response.toString());
//                            e.printStackTrace();
//                        }
                    }
                }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
//                mTextView.setText(mCurrentPhotoPath +"That didn't work!");
            }
        }){
            @Override
            // online tutorial uses some strange syntax in the angular brackets. Changed it to this instead.
            public Map<String, String> getHeaders() throws AuthFailureError {
                HashMap<String, String> headers = new HashMap<String, String>();
                headers.put("Content-Type", "application/json");
                headers.put("app_id",app_id);
                headers.put("app_key", app_key);
                return headers;
            }
        };

        // Add the request to the RequestQueue.
        mRequestQueue.add(jReq);
    }

}
